server/src/tests/integration.rs

When you partially run the integration test not all the artifacts are created. So the artifacts don't get fully cleared up for the next run because the `cleanup_files()` function quietly fails when a file doesn't exist, so it doesn't get a chance to delete rest of the artifacts.
- Remove the files and folders in the order they are created
Tested integration test step by step to check the order of artifacts created

Remove integration test artifacts in the order created

---

sdk/hardhat-example/yarn.lock
sdk/hardhat-moved/package.json
sdk/hardhat-moved/src/index.ts
sdk/hardhat-moved/yarn.lock

Adds a BCS enum serialization over the module bytecode to match the expected script or module execution selection. Closes #133 
- imports a `bcs` package
- Serializes the module inside the `ScriptOrModule` enum
Verified to make sure the transaction test BCS bytecode matches the SDK output.

Serialize deployed bytecode with higher level script or module enum

---

.github/workflows/build_and_run_tests.yaml
.github/workflows/clippy_check.yaml
.github/workflows/format_check.yaml

Now that the repo is public, we can switch back to running the actions on Github machines.
- Change `runs-on` back to default `ubuntu-latest`
The PR's checks will run the checks

chore: Switch back to Github runners

---

engine-api/src/method_name.rs
engine-api/src/methods/chain_id.rs
engine-api/src/methods/mod.rs
engine-api/src/request.rs
moved/src/state_actor.rs
moved/src/types/state.rs

Returns the Moved Network chain ID for the `eth_chainId` call. Part of https://github.com/MovedNetwork/op-move/issues/47
- Return a static response. There's no need to go through the state channel.
- Added a unit test for the `execute` method
- Tested with the integration test. Call to `eth_chainId` returns the chain id in the `op_move_response` as below:
```json
{
"request": {
"jsonrpc": "2.0",
"id": 1,
"method": "eth_chainId"
},
"geth_response": {
"jsonrpc": "2.0",
"id": 1,
"result": "0xa455"
},
"op_move_response": {
"id": 1,
"jsonrpc": "2.0",
"result": "0x194"
},
"port": "9551"
}
```

feat: Chain Id Ethereum API

---

Cargo.lock
engine-api/Cargo.toml
engine-api/src/method_name.rs
engine-api/src/methods/get_balance.rs
engine-api/src/methods/mod.rs
engine-api/src/request.rs
moved/src/move_execution/eth_token.rs
moved/src/move_execution/mod.rs
moved/src/state_actor.rs
moved/src/types/session_id.rs
moved/src/types/state.rs

Returns the requested account balance from `eth_token`. Part of #47
- Create a new engine API method
- Open up `eth_token`'s quick balance lookup and use it to implement get balance API
- Added a few block number parsing tests since they can be string literal or a hex number ie. `"latest"`, `"0x1"`
- Made sure the API gets called via the integration test and an external client like Postman
While testing with the integration test, noticed that the `state_channel` gets closed after a few requests. This is happening at the top level server requests and it happens even without this API. Haven't found a solution yet and looking into this issue. If a solution comes up we can include it in this PR or we create a separate bug issue for it.

feat: Get balance Ethereum API

---

moved/src/move_execution/canonical.rs
moved/src/types/session_id.rs
moved/src/types/transactions.rs

While working on #143 I noticed a TODO left on `SessionId` which should have been fixed as part of #122 . This is an oversight on my part so I am fixing it here.
- Include script hash in the `SessionId` when available.

Fix(transactions): Include script hash in session ID when it is present

---

server/src/tests/integration.rs

Running `cleanup_files` at the start of the integration test is meant to make sure it is starting from a good state, even if it failed at a random point previously. This means that some of the files may not exist and therefore we want to simply ignore all errors related to deleting those files instead of using `?` to exit the function early.
- Integration test

Fix(integration-test): Attempt to clean all files instead of bailing

---

Cargo.lock
Cargo.toml
moved/Cargo.toml
moved/src/genesis/config.rs
moved/src/genesis/framework.rs
moved/src/genesis/l2_contracts.rs
moved/src/genesis/mod.rs
moved/src/move_execution/evm_native.rs
moved/src/move_execution/mod.rs
server/src/lib.rs

This PR extends the genesis process to include deploying the EVM contracts coming from OP stack. These contracts are taken directly from the `genesis.json` file created by `op-node`. For the purpose of testing in the `moved` module, a new file is added to `moved/src/tests/res`. This file comes from the genesis file generated by the integration test. The integration test itself uses the file it generates.
The reason to re-use the same file to initialize op-move as is used for op-geth is because we want op-move to essentially be a drop-in replacement for op-geth.
- OP stack L2 EVM contracts included in Moved genesis state
Existing tests (including integration test)
There are a few new TODOs added in this PR, but they are P2 (not devnet blocking) in my opinion.

Feat(genesis): Deploy L2 EVM contracts at genesis

---

engine-api/src/methods/chain_id.rs
engine-api/src/methods/forkchoice_updated.rs
engine-api/src/methods/get_balance.rs
engine-api/src/methods/get_block_by_hash.rs
engine-api/src/methods/get_block_by_number.rs
engine-api/src/methods/get_payload.rs
engine-api/src/methods/new_payload.rs
engine-api/src/methods/send_raw_transaction.rs
moved/src/block/in_memory.rs
moved/src/block/mod.rs
moved/src/block/root.rs
moved/src/state_actor.rs
moved/src/types/state.rs
server/src/lib.rs

- Separate commands and queries in `StateActor`
- Introduce new `BlockQueries` trait specialized for dealing with block fetching
- Share context with both `BlockRepository` and `BlockQuery` to avoid introducing locks by moving the ownership one layer above
Part of #47

feat: Implement block fetching queries and integrate with JSON-RPC API methods

---

engine-api/src/method_name.rs
engine-api/src/methods/get_nonce.rs
engine-api/src/methods/mod.rs
engine-api/src/request.rs
moved/src/move_execution/mod.rs
moved/src/move_execution/nonces.rs
moved/src/state_actor.rs
moved/src/types/state.rs

Implementation for `eth_getTransactionCount` RPC method in op-move.
- New Query type for getting account nonces
- New quick_get_nonce API
- New test in the same style as other RPC modules

Feat(rpc): implementation for eth_getTransactionCount

---

moved/src/block/in_memory.rs
moved/src/block/root.rs
moved/src/state_actor.rs

Since the trait implementation exist only for one specialization of the generic type, it makes sense for it to be associated type rather than a generic parameter.
- Convert `Storage` generic parameter into associated type

refactor(block): Convert `Storage` generic parameter into associated type

---

engine-api/src/methods/get_block_by_hash.rs
engine-api/src/methods/get_block_by_number.rs
engine-api/src/schema/eth/block.rs
moved/src/block/in_memory.rs
moved/src/block/root.rs
moved/src/state_actor.rs
moved/src/types/state.rs
moved/src/types/transactions.rs

Implement `include_transactions` parameter for block fetching
- Converts the transactions into its full RPC representation
- Computes hashes if full transactions are not included

feat(eth-api): Implement `include_transactions` parameter for block fetching

---

sdk/hardhat-moved/src/index.ts

Deploying a contract through the SDK fails the bytecode version verification. The current CLI uses version 7, but `op-move` requires version 6 until we upgrade the Aptos repo tag to the latest.
Explicitly provide the version in the compilation command.
✓ Tested the compiled module code in `eth_estimateGas` test.

Fix(sdk): Match bytecode version to default 6

---

moved/src/state_actor.rs

In block fetching, the query and the function call and all other parameters except height are always the same. For better readibility, this change rearranges the code to reflect that fact.
- Merge the calls to block fetching by number as it only differs in the block number

refactor: Merge the calls to block fetching by number as it only differs in the block number

---

Cargo.lock
Cargo.toml
engine-api/src/json_utils.rs
engine-api/src/methods/estimate_gas.rs
engine-api/src/methods/mod.rs
moved/src/move_execution/mod.rs
moved/src/state_actor.rs
moved/src/types/state.rs
moved/src/types/transactions.rs

Accept real estimate gas requests by simulating the transaction and returning the gas used.
- Simulate a transaction in `state_actor`.
- Use real module code as input, taken from SDK counter example.
- Normalize transaction request from user.
- Update `alloy` features to support random B256 generation.
✓ Unit test is updated with a real deployment example.

Feat(rpc): Simulate transaction for gas estimation

---

engine-api/src/methods/call.rs
engine-api/src/methods/mod.rs
moved/src/move_execution/canonical.rs
moved/src/move_execution/evm_native/tests.rs
moved/src/move_execution/mod.rs
moved/src/move_execution/simulate.rs
moved/src/move_execution/tests/framework.rs
moved/src/move_execution/tests/mod.rs
moved/src/move_execution/tests/transaction.rs
moved/src/move_execution/tests/utils.rs
moved/src/state_actor.rs
moved/src/types/state.rs
moved/src/types/transactions.rs

`eth_call` implementation by simulating an entry function or script transaction. Part of #47.
- `call_transaction` method to execute entry fn or script input
- `deploy_contract` helper test method to set up `eth_call` test
- Tests for entry fn and script bytecode inputs
✓ New tests for entry fn and script
Refactored `simulate_transaction` into `simulate.rs` under `move_execution`.

Feat(rpc): Implement eth_call by transaction simulation

---

engine-api/src/schema/engine.rs
moved/src/state_actor.rs
moved/src/types/state.rs

Adds the `withdrawals_root` to the block header. This is required for `op-batcher` to work properly with `op-move`.
- Use `alloy` to compute withdrawals root
- Continued integration testing work
I'm not sure if this implementation is totally right (the withdrawals might need a different serialization than the default for example), but it does work when the withdrawals array is empty, which is the only case we consider for now. We can continue iterating on this when we actually have withdrawals.

Fix: Include withdrawals root in block header

---

engine-api/src/jsonrpc.rs
engine-api/src/methods/get_balance.rs
engine-api/src/methods/get_nonce.rs
engine-api/src/methods/get_payload.rs
engine-api/src/methods/mod.rs
engine-api/src/methods/new_payload.rs
moved/src/block/in_memory.rs
moved/src/genesis/config.rs
moved/src/genesis/framework.rs
moved/src/genesis/l2_contracts.rs
moved/src/genesis/mod.rs
moved/src/move_execution/gas.rs
moved/src/move_execution/mod.rs
moved/src/move_execution/nonces.rs
moved/src/move_execution/state.rs
moved/src/move_execution/tests/mod.rs
moved/src/move_execution/tests/utils.rs
moved/src/state_actor.rs
moved/src/state_actor/queries.rs
moved/src/storage.rs
moved/src/types/state.rs
server/src/lib.rs

Implements historical lookup of balances and nonces from the blockchain state.
- Add state queries for balance and nonce retrieval of any known block height.
- Unit test of endpoint
- Unit test of state actor
- Unit test of state queries

feat: Add state queries for balance and nonce retrieval of any known block height

---

README.md
server/src/tests/integration.rs

Just little fixes for the setup that I noticed while bootstrapping from scratch.
- Mention `foundry cast` as a requirement
- Unify preparation steps for geth and op-geth
- Updated paths
- Minor typos

fix: ensure `foundry cast` is in the path, minor readme changes

---

moved/src/error.rs
moved/src/move_execution/canonical.rs
moved/src/move_execution/deposited.rs
moved/src/move_execution/eth_token.rs
moved/src/move_execution/execute.rs
moved/src/move_execution/mod.rs
moved/src/move_execution/tests/transfer.rs
moved/src/types/transactions.rs

All the L2 contract requests go through this canonical transaction execution, including the withdrawal requests. This started as a way to initiate withdrawals, however it extended to handle every L2 request. Part of #98
- Handle L2 call requests in canonical transaction execution
- Burn any payable ETH value and then execute the L2 contract through `evm` Move native extension
- Implement `burn_eth` method in `eth_token`
- Return the EVM logs as transaction outcome
✓ Test to initiate a withdrawal request

Feat(L2): Generic L2 contract request handler

---

Cargo.lock
Cargo.toml
engine-api/src/jsonrpc.rs
engine-api/src/method_name.rs
engine-api/src/methods/get_proof.rs
engine-api/src/methods/mod.rs
engine-api/src/request.rs
moved/Cargo.toml
moved/src/move_execution/evm_native/mod.rs
moved/src/move_execution/evm_native/native_evm_context.rs
moved/src/move_execution/mod.rs
moved/src/state_actor.rs
moved/src/state_actor/queries.rs
moved/src/types/mod.rs
moved/src/types/queries.rs
moved/src/types/state.rs
moved/src/types/transactions.rs

Adds an implementation of `eth_getProof` to our RPC. The proofs returned are _not_ Ethereum MPT proofs, rather they are JMT proofs because we use a different Merkle tree implementation.
- `eth_getProof` rpc method
- New method on `StateQueries` trait for the `eth_getProof` method
- Basic sanity test in `get_proof.rs`
- Integration/devnet testing
I needed to redefine some types from the `jmt` library because they have private fields that I need access to when constructing the output for `eth_getProof`.

Feat(rpc): eth_getProof implementation

---

Cargo.lock
Cargo.toml
storage/Cargo.toml
storage/src/lib.rs
storage/src/trie.rs
storage/tests/collision.rs
storage/tests/common.rs

Introduces integration tests into the `storage` crate.
- Initialize directory for integration tests in `storage` trait
- Declare `common` module with code for creating empty database for testing
- Add test that interacts with file system using `rocksdb` that simulates the situation where the same key used for storing *state root* is used through the `DB` trait of the `eth_trie` crate and test that nothing was overwritten.

test(storage): Test that there is no collision between different column families

---

Cargo.lock
moved/src/block/root.rs
storage/Cargo.toml
storage/src/all.rs
storage/src/block.rs
storage/src/lib.rs
storage/src/trie.rs

Implements storing blocks inside `rocksdb`.
- Added `BlockRepository` implementation backed by `rocksdb`
- Added new column family for blocks into `rocksdb` so that they have separate isolated namespace to avoid collision with keys for other purposes
- Added test for column family name uniqueness

feat(storage): Implement block repository

---

moved/src/move_execution/canonical.rs
moved/src/move_execution/deposited.rs
moved/src/move_execution/evm_native/tests.rs
moved/src/move_execution/mod.rs
moved/src/move_execution/simulate.rs
moved/src/move_execution/tests/transaction.rs
moved/src/move_execution/tests/transfer.rs
moved/src/move_execution/tests/utils.rs
moved/src/state_actor.rs
moved/src/types/transactions.rs

Changes the design of our transaction execution entry points by making them use only a single argument.
- Introduce the concept of an input struct for executing transactions
- Use the input structs for deposit and for canonical transaction execution
- Update all usages
- Clear `#[allow(clippy::too_many_args)]` on the affected places

refactor: Resolve `clippy::too_many_args` warning for transaction execution

---

moved/src/move_execution/canonical.rs
moved/src/move_execution/mod.rs
moved/src/move_execution/simulate.rs

Changes the design of our transaction verification function by making it use only a single argument.
- Introduce the concept of an input struct for verification of transactions
- Use the input structs for canonical transaction verification
- Update all usages
- Clear `#[allow(clippy::too_many_args)]` on the affected places

refactor: Resolve `clippy::too_many_args` warning for transaction verification

---

engine-api/src/methods/estimate_gas.rs
server/src/lib.rs

Browsers require CORS support when making calls to the server.
Viem client calls `eth_estimateGas` without the block number assuming the latest.
- Receive calls from anywhere with CORS
- Accept estimate gas calls without the block number parameter
✓ Unit tests, clippy and format checks all pass

Feat(server): Support cross origin CORS calls

---

moved/src/move_execution/deposited.rs

Resolves warnings produced when compiling non-test builds
- Add compiler flag to test only imports

fix: Add compiler flag to test only imports

---

server/Cargo.toml

In case this is wanted, this PR changes the name of the output binary to `op-move` which should align nicely with the rest of the op stack.
When building for default target with release profile, the produced binary executable will be `./target/release/op-move`
- Rename target binary `moved_server` => `op-move`
```
cargo run --bin op-move
```

build(server): Rename target binary `moved_server` => `op-move`

---

api/src/json_utils.rs
api/src/methods/block_number.rs
api/src/methods/call.rs
api/src/methods/get_balance.rs
api/src/methods/get_block_by_hash.rs
api/src/methods/get_block_by_number.rs
api/src/methods/get_payload.rs
api/src/methods/get_transaction_receipt.rs
api/src/methods/new_payload.rs

The endpoint implementation contains parameter parsing logic, that contains a large portion of duplicated code.
In this PR we use generic return types to generalize and remove these duplicated parsing functions.
Targets only cases where the argument count is exact with no further logic.
- Remove duplicate custom parsing logic and generalize it into a generic version

refactor(api): Generalize JSON-RPC params parsing

---

api/src/methods/get_payload.rs
api/src/methods/get_transaction_by_hash.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
api/src/schema/eth.rs
moved/src/block/in_memory.rs
moved/src/in_memory.rs
moved/src/lib.rs
moved/src/state_actor.rs
moved/src/transaction/in_memory.rs
moved/src/transaction/mod.rs
moved/src/transaction/read.rs
moved/src/transaction/write.rs
moved/src/types/state.rs
server/src/lib.rs

* Adds append-only repository and query for fetching by hash.
* Allows for querying transactions using API.
* Includes in-memory implementation.
- Add write and read model for transactions
- Add in-memory implementations
- Include the model in `StateActor`
- Return proper responses in `api` endpoint
- Fill-in all missing fields
In this version, the transactions are stored twice. Once in their own memory space and once as a part of blocks.
This can be mitigated, but doing so would increase the amount of changes in this high priority PR as well as time to finish and review it.
Therefore we can conclude that it's better to target it as a separate issue.

feat: Add transaction reading and writing

---

moved/src/transaction/write.rs
storage/src/all.rs
storage/src/lib.rs
storage/src/transaction.rs

Adds support for transaction read and write model via `rocksdb`.
- Implements transaction read and write model using `rocksdb`
- Extends `rocksdb` with new column family for transactions

feat(storage): Implement transaction reading and writing using `rocksdb`

---

moved/src/block/in_memory.rs
moved/src/block/root.rs
moved/src/transaction/in_memory.rs
moved/src/transaction/write.rs
moved/src/types/state.rs
storage/src/block.rs
storage/src/transaction.rs

Fills-in missing gas price in transactions that are a part of block responses.
The recently added transaction response contains the `effective_gas_price` so this PR unifies this code path.
It is a step closer to removing transactions from blocks altogether and only use their own dedicated storage.
- Unify code paths for pure transaction responses and transaction responses inside blocks

feat: Add `effective_gas_price` into transactions inside block responses

---

moved/src/receipt/in_memory.rs
moved/src/receipt/mod.rs
moved/src/receipt/read.rs
moved/src/receipt/write.rs
moved/src/state_actor.rs

Cuts out dependency on block to construct receipt response. Also removes transaction from receipt and instead keeps only needed information.
The result of this is that the receipts are more cleanly isolated.
This is a ground work to make receipts serializable.
* Rename `TransactionWithReceipt` to `ExtendedReceipt`
* Remove dependency on block
* Remove transaction

refactor: Change `TransactionWithReceipt` into `ExtendedReceipt`

---

sdk/hardhat-moved/src/index.ts

These TODOs are not necessary, because the current way of reading the files is quite good. It doesn't need a result based interface.
- Remove unnecessary `TODO` items

Clean: Remove unnecessary TODOs in SDK

---

api/src/method_name.rs
api/src/request.rs
api/src/schema/engine.rs

Closes #48 
Removes V2 engine methods and schema.
These were never implemented and not needed to be.
- Removes V2 engine method names
- Removes V2 engine schema structs

refactor(api): Remove V2 engine methods and schema

---

api/src/method_name.rs
api/src/request.rs
server/src/lib.rs
server/src/tests/get_proof.rs

Closes #43 
The `enigne_` APIs should be callable only on the secure port `8551` with the JWT token.
- Restrict access to the engine API only to the auhenticated endpoint
- Keep public endpoints open to all other endpoints.

feat(api): Protect engine API access only to the authenticated port `8551`

---

api/src/method_name.rs
api/src/methods/estimate_gas.rs
api/src/methods/gas_price.rs
api/src/methods/mod.rs
api/src/request.rs

Viem SDK is the official client for Optimism. In order to make deposits and withdrawals estimate gas and gas price APIs should work as expected.
- Return min 21,000 for gas estimate
- Respond to gas price API
✓ Viem SDK examples for [deposit](https://viem.sh/op-stack/guides/deposits) and [withdrawal](https://viem.sh/op-stack/guides/withdrawals) work now.
✓ Unit tests and other checks pass.

Fix: Provide API responses for Viem SDK

---

Cargo.lock
Cargo.toml
api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
genesis-image/build.rs
genesis/src/framework.rs
genesis/src/l2_contracts.rs
genesis/src/lib.rs
moved/src/block/in_memory.rs
moved/src/block/root.rs
moved/src/receipt/in_memory.rs
moved/src/receipt/read.rs
moved/src/state_actor.rs
moved/src/state_actor/queries.rs
moved/src/transaction/write.rs
server/Cargo.toml
server/src/dependency.rs
server/src/lib.rs
state/src/lib.rs
storage/Cargo.toml
storage/src/block.rs
storage/src/generic.rs
storage/src/lib.rs
storage/src/receipt.rs
storage/src/state.rs
storage/src/transaction.rs
storage/src/trie.rs

Closes #216 
Includes all the newly created dependencies implemented using `rocksdb`.
Allows switching between in-memory and rocksdb configuration using `storage` feature flag
- Integrate dependencies that use `rocksdb` as a backing storage engine
- Allow switching between in-memory and rocksdb configuration using `storage` feature flag
You may now launch the node
* Using in-memory:
```
cargo run --bin op-move
```
* Using rocksdb:
```
cargo run ---bin op-move --features storage
```

feat(server): Integrate dependencies that use `rocksdb` as a backing storage engine

---

server/src/tests/integration.rs

Avoids holding for user input when asking to add transactions with no code
- Add `--non-interactive` flag into `forge` deploy L1 contracts stage of the integration test

test(server): Turn on non-interactive flag in `forge`

---

moved/src/move_execution/execute.rs

Closes #61 
After reviewing nested references invariant, I conclude that it is valid based on the official Move book.
- Annotate the disallowment of nested references
- Remove TODO comment referencing this issue

docs: Annotate the disallowment of nested references

---

moved/src/move_execution/execute.rs
moved/src/move_execution/layout.rs
moved/src/move_execution/mod.rs

Closes #59
When executing Move entry function, the parameters that go into that function have certain invariants that need to be checked.
This, however, applies only to certain types. The type information is available before value deserialization happens. This allows us to optimize-away the deserialization if the type has no value-based invariants.
- Introduce new function to analyse move type layout for value-based invariants
- Optimize away value deserialization if this function reports no vaule-based invariants

perf: Skip value deserialization if Move param type has no value-based invariants

---

moved/src/state_actor.rs
moved/src/state_actor/queries.rs
server/src/dependency.rs
server/src/lib.rs
storage/src/all.rs
storage/src/generic.rs
storage/src/lib.rs
storage/src/state.rs

Adds new `StateQueries` implementation backed by `rocksdb`
- Adds new `StateQueries` implementation backed by `rocksdb`
- Adds new `OnTxBatch` callback specific to the `rocksdb` implementation of `StateQueries`
- Moves some trait types into type aliases to avoid clippy warning about complex types
- Uses this implementation when building with `--features storage`.

feat(storage): Implement `StateQueries` using `rocksdb`

---

server/src/lib.rs

Load balancers make health check requests to include VMs in the backend. The requests use GET method. This PR responds to any GET request with 200 success status and `healthy` response.
- Shortcut server response if it's a GET request with `healthy` string response
✓ Tested on load balancer and the VM got included after this change

Feat(server): Health check response on GET requests

---

.gitignore
.gitmodules
README.md

Using submodules is unneccessary and brings in complexity and messes up the staging area.
It is also inconsistent with other dependencies like `geth` that are cloned without submodule.
This PR gets rid of the submodule setup while keeping everything adjusted to cloning and makes it all consistent.
- Remove submodules from the repository
- Adjust readme instructions for the cloning
- Ignore optimism directory in git to avoid adding it and including it in git status

build: Remove optimism submodule

---

.dockerignore

Avoids copying unnecessary files and directories that are created by containers, therefore will never be used in the image build process.
In a future version there will likely be a database volume which will be very large, slowing down the build process significantly.
- Add `docker/volumes` to `.dockerignore`
:green_circle: `docker compose build`

build(docker): Ignore volumes directory from the docker build context

---

genesis/src/config.rs
genesis/src/lib.rs
server/src/lib.rs

Makes the `GenesisConfig` self-contained instead of relying on external file.
Furthermore, the default file is embedded instead of being read at runtime.
Resolves one TODO item.
- Add `Genesis` into `GenesisConfig`
- Embed default `Genesis` into the binary
:green_circle: `docker compose build && docker compose up-d`

refactor(genesis): Add L2 contract genesis to `GenesisConfig`

---

storage/heed/src/block.rs
storage/heed/src/lib.rs
storage/heed/src/receipt.rs

Adds the receipts backing storage implementation using `heed`.
- Implement `ReceiptRepository` using `heed`
- Implement `ReceiptQueries` using `heed`

feat(storage): Implement `ReceiptRepository` and `ReceiptQueries` using `heed`

---

storage/heed/src/lib.rs
storage/heed/src/transaction.rs

Adds the transactions backing storage implementation using `heed`.
- Implement `TransactionRepository` using `heed`
- Implement `TransactionQueries` using `heed`

feat(storage): Implement `TransactionRepository` and `TransactionQueries` using `heed`

---

storage/heed/src/block.rs

Adds the `BlockQueries` backing storage implementation using `heed`.
Contrary to the repository implementation, this one is dependent on the transaction implementation, that's why it is split.
- Implement `BlockQueries` using `heed`

feat(storage): Implement `BlockQueries` using `heed`

---

storage/heed/src/lib.rs
storage/heed/src/payload.rs

Adds the payload backing storage implementation using `heed`.
- Implement `PayloadQueries` using `heed`

feat(storage): Implement `PayloadQueries` using `heed`

---

Cargo.lock
storage/heed/Cargo.toml
storage/heed/src/generic.rs
storage/heed/src/lib.rs
storage/heed/src/trie.rs

Adds the merkle trie backing storage implementation using `heed`.
- Implement `eth_trie::DB` using `heed`

feat(storage): Implement `EthTrie` using `heed`

---

Cargo.lock
storage/heed/Cargo.toml
storage/heed/src/block.rs
storage/heed/src/lib.rs
storage/heed/src/payload.rs
storage/heed/src/state.rs
storage/heed/src/transaction.rs
storage/heed/src/trie.rs

Adds the state backing storage implementation using `heed`.
- Implement `State` using `heed`

feat(storage): Implement `State` using `heed`

---

.gitignore
Cargo.lock
Cargo.toml
app/src/actor.rs
docker/Dockerfile.op-move
execution/src/eth_token.rs
server/Cargo.toml
server/src/dependency/heed.rs
server/src/dependency/mod.rs
storage/heed/Cargo.toml
storage/heed/src/all.rs
storage/heed/src/block.rs
storage/heed/src/generic.rs
storage/heed/src/lib.rs
storage/heed/src/payload.rs
storage/heed/src/receipt.rs
storage/heed/src/state.rs
storage/heed/src/transaction.rs
storage/heed/src/trie.rs

Follows-up on previous PRs about LMDB implementation and integrates it with the server into an executable binary.
- Add `server` configuration with `heed` storage
- Add transaction commit per database call
- Create LMDB environment with 1 TiB total size limit
Long running `docker compose down && docker compose build && docker compose up -d`
Collecting statistics using `pidstat`
To run with LMDB:
```
cargo run --bin op-move --features storage-lmdb
```

feat(server): Integrate with LMDB persistent backing storage engine using `heed`

---

Cargo.toml
docker/Dockerfile.op-move
server/Cargo.toml
server/src/dependency/mod.rs
server/src/dependency/rocksdb.rs

It is no longer clear from just `storage` flag what persistent backend it is pointing to, since there are now multiple.
To make the feature flag names consistent and explicit, this PR unifies the naming.
Addresses https://github.com/MovedNetwork/op-move/pull/294#discussion_r1976258219
The reasoning behind the naming is explained here https://github.com/MovedNetwork/op-move/pull/294#discussion_r1976523224
- Rename the old `storage` flag to `storage-rocksdb` to make it clear which backend it is poiting to.
- Add `storage` flag pointing to `storage-lmdb` as the default storage backend.

build: Mention storage backend name in the feature flag

---

storage/heed/src/all.rs
storage/heed/src/block.rs
storage/heed/src/generic.rs
storage/heed/src/payload.rs
storage/heed/src/receipt.rs
storage/heed/src/state.rs
storage/heed/src/transaction.rs
storage/heed/src/trie.rs

Having a custom type for a database gives us a better modeling opportunities. It allows us to only permit behavior that we expect to be using. Thanks to zero-cost abstractions, this comes at no performance cost.
What's more it gives us a better control and transparency over which calls are being made. When all the calls to database go through our type, we can extend the calls to always include our custom behavior. For example, we can log every call or place a debugger breakpoint in there. This helps to debug a performance issue, for example.
It also reduces code duplication of redundant database opening calls and error handling.
- Add wrapper type for `heed::Database`
- Add extension traits for opening known databases
- Implement extension traits for `heed::Env` …

feat(storage-heed): Wrap database in a custom type

---

docker/Dockerfile.geth
docker/geth.sh
docker/keystore.sh
execution/src/transaction.rs
server/src/lib.rs

A few fixes combined.
- Cloud logs are better when they are in a single line
- `eth_estimateGas` transaction input can come from either `input` or `data`
- Serve the Devnet with the same key file so the faucet address doesn't change
✓ Docker works
✓ Hardhat is able to deploy by calling `eth_estimateGas`
✓ Cloud logs come through one request at a time, instead of each line in the request JSON being split into a separate log

Fix: Simplify cloud logs and get eth_estimateGas tx input data

---

server/src/lib.rs

Start sending custom headers in a `map` starting with the `Content-Type: application/json` header.
- Send `Content-Type` header in server response to clients only for now.
REST clients detect the content type and parse the response automatically accordingly. Here's how the response shows up on a client:
| With Header | Without |
|--|--|
| <img width="432" alt="Screenshot 2025-03-12 at 2 52 55 PM" src="https://github.com/user-attachments/assets/439ae900-2957-4f8c-a8a3-ebaef6cda25d" /> | <img width="430" alt="Screenshot 2025-03-12 at 2 55 27 PM" src="https://github.com/user-attachments/assets/6cb6e16b-f6f1-4b68-8378-41270857d545" /> |

Feat(server): Send content type header in the response

---

api/src/methods/forkchoice_updated.rs
api/src/methods/get_block_by_number.rs
api/src/methods/get_payload.rs
api/src/methods/get_transaction_by_hash.rs
api/src/methods/get_transaction_receipt.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
api/src/request.rs
app/src/actor.rs
app/src/input.rs
server/src/dependency/heed.rs
server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs
server/src/dependency/shared.rs
server/src/lib.rs
server/src/tests/get_proof.rs

Unblocks forkchoice API handler from waiting on generated payload ID.
From a general point of view, unblocks any API handler that sends commands from waiting on response as no command should have a response to begin with. This PR makes it so that this invariant holds true.
The application layer receives two different kinds of messages. 
* **Queries:** Immutable and always returns value
* **Commands:** Mutable and never returns value
Working with this assumption, the commands are always handled asynchronously in a background task and do not block the thread that dispatched it - the RPC API method handler. In this way the method handler can return without waiting for the task to finish as there is no reason to wait.
This assumption, however, is broken by one command, which is the …

perf: Generate payload ID before starting block build

---

genesis-builder/framework/l2/sources/BaseFeeVault.move
genesis-builder/framework/l2/sources/CrossL2Inbox.move
genesis-builder/framework/l2/sources/GasPriceOracle.move
genesis-builder/framework/l2/sources/GovernanceToken.move
genesis-builder/framework/l2/sources/L1Block.move
genesis-builder/framework/l2/sources/L1BlockNumber.move
genesis-builder/framework/l2/sources/L1FeeVault.move
genesis-builder/framework/l2/sources/L2CrossDomainMessenger.move
genesis-builder/framework/l2/sources/L2ERC721Bridge.move
genesis-builder/framework/l2/sources/L2StandardBridge.move
genesis-builder/framework/l2/sources/L2ToL1MessagePasser.move
genesis-builder/framework/l2/sources/L2ToL2CrossDomainMessenger.move
genesis-builder/framework/l2/sources/OptimismMintableERC20Factory.move
genesis-builder/framework/l2/sources/OptimismMintableERC721Factory.move
genesis-builder/framework/l2/sources/ProxyAdmin.move
genesis-builder/framework/l2/sources/SequencerFeeVault.move
genesis-builder/l2_move_template.hbs
genesis-builder/src/generate.rs

Make parameter encoding step more efficient by skipping it for empty args in L2 contracts.
Fixes #316.
- Template file change
- New boolean flag in generation logic
Old tests pass as they should.

fix(move): do not encode empty args

---

api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
app/Cargo.toml
app/src/actor.rs
app/src/dependency.rs
app/src/lib.rs
server/src/dependency/heed.rs
server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs
server/src/dependency/shared.rs
server/src/lib.rs

Closes #174 
Groups all application dependencies into one object.
* The `StateActor::new` has a lot of parameters. There is a parameter per dependency. Since state actor orchestrates all queries and commands, it is dependent on everything.
* The creation of these dependencies has several variants for different kinds picked by feature flags. It is not standardized by any language tool, but it implicitly relies on the assumption that functions for creating these dependencies are named the same in every variant.
* The `StateActor::new` triggers a warning from `clippy` that is supressed.
* `StateActor` is an exclusive owner of all these dependencies. Delegating the responsibility of specifying and holding all application dependencies and making them shareable is a prerequisite for parallel …

refactor: Reduce all application dependencies into one

---

app/src/actor.rs
app/src/dependency.rs
server/src/dependency/heed.rs
server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs

Reduces overhead for creating callback functions.
The type for creating callbacks is pretty complex and requires heap allocation for static values.
The callback functions, when used as `Box<dyn Fn(&mut self, ...)>` require mutable borrowing of `self`. But calling the function also requires `self` to be borrowed. Therefore, calling it and passing `self` or a field on `self` as argument, means that `self` is borrowed twice, triggering a compile error.
To circumvent this, an indirection is introduced `Box<dyn Fn(...) -> Box<dyn Fn(&mut self)>>` which is a function that creates a function. In this way, the created function is a new value that is not owned by `self` and therefore can accept `self` or fields on `self` as arguments.
The callback is reduced to a static reference. In this way, it …

perf: Remove indirection and heap allocation from callbacks

---

genesis-image/build.rs

I've noticed that if I was fiddling with the the Aptos bundle by rerunning the genesis builder and swapping the .mrb file, the tests would keep failing even when they shouldn't unless I change something else in the code. This was due to the image in the out dir not being updated on changes. This can be solved by a little tweak. 
- Just a single build directive for the build script
No new tests, but should be in accordance with the [spec](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed).

feat: trigger image rebuild on genesis change

---

README.md

Just a small one with new stumbling blocks I found out when recreating the environment on a new machine a while ago.
- Mention max Go version (this will be obsoleted with Optimism bump)
- Mention the need to call `submodule init` in the optimism repo itself as it pulls in openzepellin contracts and such

fix: clarify requirements for setup steps in readme

---

api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
app/src/actor.rs
app/src/command.rs
app/src/dependency.rs
app/src/lib.rs
app/src/query.rs
app/src/tests.rs
server/src/lib.rs

Separates application scenarios from `StateActor`
The `StateActor` is responsible for receiving and processing messages. In addition, it is also responsible for implementing whatever scenario the messages are supposed to execute. It should be responsible for only one of these things.
A prerequisite for a follow-up work is to be able to launch scenarios from other ways than going through `StateActor`.
The scenarios cannot be executed without going through the `StateActor` pipeline.
* Define methods for commands and queries in `Application`
* Move remaining state into `Application`

refactor(app): Separate all application scenarios from `StateActor` into `Application`

---

Cargo.lock

I ran `cargo update` again because there is a new version of tokio out that fixes [a bug](https://rustsec.org/advisories/RUSTSEC-2025-0023.html).
- `cargo update`

Chore(deps): Upgrade tokio to v1.44.2

---

Cargo.lock

The PR updates our dependencies again because `crossbeam-channel` has [a bug](https://rustsec.org/advisories/RUSTSEC-2025-0024.html).
- `cargo update`

Chore(deps): updrade crossbeam-channel to v0.5.15

---

docker/Dockerfile.op-move

* Speeds up the build by downloading the proper toolchain as default
* Removes unused toolchain
- Parse toolchain version from `rust-toolchain` file
```
```

build(docker): Parse rust toolchain from workspace file

---

api/src/json_utils.rs
api/src/jsonrpc.rs
api/src/methods/forkchoice_updated.rs
api/src/methods/get_payload.rs
api/src/methods/get_transaction_by_hash.rs
api/src/methods/get_transaction_receipt.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
api/src/methods/send_raw_transaction.rs
api/src/request.rs
app/src/factory.rs
app/src/lib.rs
app/src/queue.rs
server/src/lib.rs
server/src/main.rs
server/src/tests/get_proof.rs
server/src/tests/integration.rs

Maintains the consistency of the server application state.
If the application is running we want some guarantee that it is in a consistent state that is ready to be used.
When a panic happens during the processing of a command, it closes the command channel.
However, the server remains running and still accepts requests to RPC endpoints.
In this application state, if a command is sent to the queue, it fails and returns an RPC error. Such case would be valid if that would be a user error. A command should never panic based on a user input, therefore this does not classify as a user error and should not result in a RPC error response.
A server is launched while listening to a graceful shutdown listener. That listener listens to a signal that is turned on when the background thread …

feat: Shut the server down if command queue panics

---

api/src/methods/call.rs
evm-ext/src/events.rs
evm-ext/src/lib.rs
execution/src/simulate.rs
server/src/tests/integration/erc20.rs

Only return the results of the transaction in bytes without Move value layout. This is the standard way the results are returned even though `session` execution also returns the layout. This response works better when it comes to parsing on the client side. Closes #322 
- Return `call_transaction` response bytes.
- Create EVM native outcome layout to be used in integration test.
- Fix integration test to parse the balance and allowance values from the returned bytes.
✓ Integration test passes.

Fix(tx): Return only values from call without layout

---

docker/Dockerfile.op-move

`op-move` fails to run with `docker compose` and the error message is:
```
Tokens list should parse: Path: "/volume/execution/src/tests/res/bridged_tokens_test.json"
No such file or directory (os error 2)
```
- Copy the bridged token JSON file that's used in genesis config
✓ Docker compose runs successfully on the cloud

Fix(docker): Copy bridged token file

---

api/src/methods/forkchoice_updated.rs
api/src/methods/get_payload.rs
api/src/methods/mod.rs
app/src/actor.rs
app/src/command.rs
app/src/input.rs
app/src/tests.rs
server/src/lib.rs

While observing the commands received in the app as part of making benchmarks I noticed that the `UpdateHead` command is called repeatedly in unbroken sequences with the same hash.
The command is invoked when calling `engine_forkchoiceUpdated` by `op-node`. This endpoint is called repeatedly without payload as a part of canonical chain validation process. Every time this endpoint is invoked it produces `UpdateHead` command.
This behavior is incorrect, but that is expected and recorded in the issue #63. Perhaps this way was to instead of validation assume that the op-node state is valid and make sure op-move is at the same state.
Effectively this only does one thing which is sets the head hash to the last block. It is critical that this happens. If the head pointer is not correctly …

perf(app): Remove `UpdateHead` command

---

api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
app/src/command.rs
app/src/dependency.rs
app/src/query.rs
app/src/tests.rs
blockchain/src/block/in_memory.rs
blockchain/src/block/root.rs
server/src/dependency/rocksdb.rs
storage/heed/src/all.rs
storage/heed/src/block.rs
storage/heed/src/generic.rs
storage/rocksdb/src/block.rs

An on-ramp to #268 is to remove `head` and `height` pointers. The reason is that these pointers are lost when the node shuts down. To resolve this, these need to be computed from persisted data instead.
- Remove `Application::height`
- Remove `Application::head`
- Add `BlockRepository::latest`
- Add `BlockQuery::latest`
```
cargo test
```
```
docker compose down && docker compose build && docker compose up -d && docker compose logs -f
```
* Endianness of `HeightKey` in `storage_heed` was switched to big endian, because otherwise the `last` iterator caps out at 256 / 0xff.

feat: Compute `head` and `height` pointers from persisted data

---

genesis-image/build.rs
genesis/src/framework.rs
genesis/src/lib.rs
server/src/lib.rs

Genesis state build should produce changes without applying them in a side-effect free manner.
The node crashes on startup when using in-memory storage backend as a consequence of applying some parts of the `ChangeSet` twice.
- Remove `&mut State` parameter from `moved_genesis::build`
- Use temporary `InMemoryState` inside `moved_genesis::build`
```
docker compose build && docker compose up -d
```
With `--feature storage` removed from `docker/Dockerfile.op-move`

fix(genesis): Do not apply `ChangeSet` to `State` on build

---

execution/src/gas.rs

After research into the OP governance docs regarding operator fees, I found out that these fields are indeed set at L1 level in the SystemConfig contract, but their storage slots and values are still 0, though it might change if some consensus baseline for them is agreed upon in the future. So #327 still needs to stay open, but I demoted it to P2 as we're not doing anything wrong yet.
- Clearer wording for the TODO

chore(gas): reword operator fee todo for clarity

---

.github/workflows/clippy_check.yaml
server/src/tests/integration/erc20.rs

I realized I accidentally broke the integration test in #358 because I forgot to remove the signer argument from the ERC-20 queries constructed in the integration test. This PR fixes the problem so the integration test passes again.
- No production code changes
- Integration test

Fix(integration): Signer arguments no longer needed in ERC-20 queries

---

server/src/dependency/heed.rs
server/src/dependency/rocksdb.rs
storage/heed/src/state.rs
storage/heed/src/trie.rs
storage/rocksdb/src/lib.rs
storage/rocksdb/src/state.rs
storage/rocksdb/src/trie.rs
storage/rocksdb/tests/collision.rs

Implements the proposed model below using a `State` implementation backed by `EthTrie`.
The storage layer should not contain any domain logic. A practical consequence of this is duplicated code, heavier maintenance burden and more complicated storage implementations.
The blockchain `State` is a trie structure, therefore it relies a lot on trie algorithms. When having multiple implementations, the only difference is the underlying key-value store. However, implementing `State` per storage engine requires to provide both key-value store and trie algorithms.
The result is that every `State` implementation duplicates knowledge that belongs in the domain layer.
```mermaid
---
title: Current model
---
classDiagram
State <|-- HeedState
State <|-- RocksDbState
State <|-- InMemoryState
class State …
```

refactor(storage): Replace all `State` implementations with `EthTrieState`

---

api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
app/src/command.rs
app/src/tests.rs
blockchain/src/state/read/tests.rs
execution/src/canonical.rs
execution/src/deposited.rs
execution/src/tests/utils.rs
execution/src/transaction.rs
genesis-image/build.rs
genesis-image/src/lib.rs
genesis/src/framework.rs
genesis/src/lib.rs
server/src/lib.rs
state/src/diff.rs
state/src/lib.rs
state/src/state.rs

Removes `apply_with_tables` and adds table changes to `apply`.
- Remove `State::apply_with_tables`
- Add `Changes` for representing a difference between states
- Include `TableChanges` in `Changes`
:green_circle: fmt
:green_circle: clippy
:green_circle: test

refactor(state): Unify `apply` and `apply_with_tables`

---

.github/workflows/build_and_run_tests.yaml

The job currently always fail due to "not enough space on device" error.
Fixes the problem in the same way as for the regular test job.
- Add "free up disk space" step to flaky job before compilation
:green_circle: Github actions

ci(flaky): Free up disk space before compilation

---

app/Cargo.toml
app/src/lib.rs
app/src/uninit.rs
blockchain/src/state/read/test_doubles.rs
blockchain/src/state/read/tests.rs

In an effort to implement two-step start up of the application, this change adds a set of dependencies uninitialized.
The two-steps are:
1. Start the server
2. Start the application
However, starting the server needs the application because the server has RPC handlers that want to send commands and perform queries.
Therefore, having a set of uninitialized dependencies is a way to be able to create the application without initializing. Real dependencies open the database, which is in conflict with having a secondary node instance accessing it too.
All of this is towards being able bring up two instances of the node on the same database to allow for zero-downtime deployment.
- Add `Uninitialized`
- Implement `Dependencies` for `Uninitialized`

feat(app): Add a set of non-operational dependencies

---

server/src/allow.rs
server/src/lib.rs

While working on different ways to distribute application and server creation, I stumbled upon this difficult to work with code path that contains duplicated code that should be shared.
This change reduces duplicated server setup code, makes it more readable and easier to work with.
- Add `serve` function for creating `warp` server
- Delegate server setup into `serve`

refactor(server): Add `serve` function that creates `warp` server

---

server/src/dependency/rocksdb.rs
storage/rocksdb/src/block.rs
storage/rocksdb/src/evm.rs
storage/rocksdb/src/evm_storage_trie.rs
storage/rocksdb/src/payload.rs
storage/rocksdb/src/receipt.rs
storage/rocksdb/src/transaction.rs

The database is implemented as a static lazily initialized variable. This gives the possibility to take `'static` references from it, which is simpler than dealing with explicit sub-static lifetimes. However, it also makes it bound to the process and cannot be reinitialized.
- Remove `'static` from `storage-heed`

feat(storage-rocksdb): Remove `'static` lifetime from database references

---

api/src/json_utils.rs
api/src/jsonrpc.rs
api/src/method_name.rs
api/src/methods/block_number.rs
api/src/methods/call.rs
api/src/methods/estimate_gas.rs
api/src/methods/fee_history.rs
api/src/methods/forkchoice_updated.rs
api/src/methods/get_balance.rs
api/src/methods/get_block_by_hash.rs
api/src/methods/get_block_by_number.rs
api/src/methods/get_nonce.rs
api/src/methods/get_payload.rs
api/src/methods/get_proof.rs
api/src/methods/get_transaction_by_hash.rs
api/src/methods/get_transaction_receipt.rs
api/src/methods/new_payload.rs
api/src/methods/send_raw_transaction.rs
api/src/request.rs
app/src/mempool.rs
app/src/query.rs
app/src/tests.rs
shared/src/error.rs

As mentioned in the discussion with @code-dogg, current treatment of `shared::Error` to `JsonRpcError` conversion was subpar, with no panicking on invariant violation and cumbersome error mapping. This PR collects all those conversions into one place and refactors some of the surrounding infrastructure around JSON RPC errors.
- More idiomatic error conversion at API execution sites
- Geth-compliant error code mapping
- Slightly reworked fee history errors
🟢 Existing API tests

refactor(api): use geth compliant codes in `JsonRpcError`

---

api/src/methods/get_transaction_by_hash.rs
api/src/methods/get_transaction_receipt.rs
app/src/dependency.rs
app/src/query.rs
app/src/tests.rs
app/src/uninit.rs
blockchain/src/block/in_memory.rs
blockchain/src/block/mod.rs
blockchain/src/in_memory.rs
server/src/dependency/heed.rs
server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs
server/src/lib.rs

This PR fixes the integration so that it works again (with all backends).
- Failing to find a transaction by hash is not an error. This is important to get right because libraries for interacting with Ethereum RPCs handle null responses differently from errors and will check for transactions by hash in a loop when waiting for a status.
- Use the same EVM account storage for both application reader and writer for the in-memory backend. This is necessary because otherwise the reader does not see the changes the writer makes. The database backends already had this property because the reader and writer refer to the same DB on-disk.
- Use `Arc<RwLock<HashMap>>` for in-memory block storage. I don't know why the `evmap` implementation doesn't work, but the integration test fails to show op_node …

Fix(integration-test): EVM storage and missing transaction handling

---

sdk/hardhat-umi/package.json
sdk/hardhat-umi/src/index.ts

Compiling with the bytecode version is not needed after upgrading the MoveVM.
The NPM package is already upgraded with this change.
- Remove bytecode version restriction from the SDK.
- Relax `hardhat` peer dependency to major version 2 instead of specific minor version.
- Renamed the package back to `@moved/hardhat-plugin` cause that's how it is used in NPM package. We will update this after we are able to rename the NPM org name.
Tested with an sample contract. The test case is explained in our [docs](https://docs.uminetwork.com/deploy-contract).

Fix(sdk): Remove bytecode version restriction

---

server/src/tests/integration.rs

Keep L1 logs in a file too, just like the others. This leaves no log messages on terminal to watch for println statements.
- Write `geth` logs to a file

Fix(integration): Write L1 geth logs to a file

---

Cargo.lock
Cargo.toml
server/args/Cargo.toml
server/args/src/declaration.rs
server/args/src/lib.rs
server/args/src/tests.rs
server/src/lib.rs

Adds a small crate that declares server settings.
- Add `umi-server-args` crate
#45

feat(server): Add `umi-server-args` crate that declares parameters for running the server

---

server/args/src/layers/file.rs
server/args/src/layers/mod.rs
server/args/src/lib.rs

Adds a `Layer` that loads config from a file using a provided parser.
- Add `FileLayer`
#45

feat(server-args): Implement `Layer` that parses files

---

server/args/src/layers/default.rs
server/args/src/layers/mod.rs
server/args/src/lib.rs

Adds a `Layer` that returns default config values that can be used as a base layer.
- Add `DefaultLayer`
#45

feat(server-args): Implement `Layer` that returns default values

---

Cargo.lock
Cargo.toml
server/Cargo.toml
server/args/src/declaration.rs
server/args/src/layers/cli.rs
server/args/src/layers/default.rs
server/args/src/layers/env.rs
server/args/src/layers/file.rs
server/args/src/lib.rs
server/args/src/stack.rs
server/args/src/tests.rs
server/src/lib.rs
server/src/main.rs
server/src/tests/integration.rs

Constructs a config stack and uses it to run the server.
- Add `umi-server-args` as a dependency of `umi-server`
- Use `ConfigBuilder` to build `Config` using a stack of `Layer`s
#45

feat(server): Build server arguments from a stack of `Layer`s of configuration sources

---

server/src/tests/integration.rs

Move the `op-move` runtime process into its own function to keep the integration test just made of steps.
- `op-move` runtime function
✓ Integration test passes.

Refactor(integration): Move op-move runtime into dedicated function

---

server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs

Fixes build error with `storage-rocksdb` feature flag on while `storage-lmdb` flag is off.
- Use proper types for `rocksdb` dependencies
:green_circle: `cargo clippy --features storage-rocksdb --all-targets`
:green_circle: `cargo clippy --features storage-lmdb --all-targets`
:green_circle: `cargo clippy --all-targets`

fix(server): Resolve misplaced types in `rocksdb` dependencies

---

server/src/dependency/heed.rs
server/src/dependency/rocksdb.rs
server/src/dependency/shared.rs

Calls fallible function for a fixed number of tries.
Removes a duplicated piece of code that was responsible for this.
- Add `fallible::retry` function
- Replace duplicated pieces of code responsible for this with a call to `fallible::retry`.

feat(server): Add `fallible::retry` function

---

app/src/block_hash.rs
server/src/dependency/heed.rs
server/src/dependency/rocksdb.rs

The server currently relies on `ApplicationReader` being stateless, i.e. not reading database to be initialized.
Not upholding this invariant breaks deployment.
This invariant was broken by the `BlockHashCache` that prefills itself on initialization.
This change makes it so that it is initialized empty.
- Make `initialize_*` functions return result instead of panicking.
- Add `new` functions to `BlockHash` structs that initialize them empty.
Might be worth looking into making the initialize step lazy initialized.

fix(server): Remove database access from dependencies for `ApplicationReader`

---

evm-ext/src/solidity_abi.rs

No changes to production code. Fixes flaky test `solidity_abi::tests::test_gas_costs`.
- Benchmark function with 100 trials and use the median duration as the metric for determining test pass/failure.
`solidity_abi::tests::test_gas_costs`
This change doesn't completely eliminate the chance of flakiness. If we assume all 100 trials are independent (perhaps not a good assumption since timing might depend on ambient system load, which could be highly correlated from moment to moment) then using the median of 100 trials essentially amplifies the pass/fail signal, as shown in the plot below. Essentially, if a single trial has a 60% chance of passing or better then median will pass close to 100% of the time, but not literally 100% of the time.

Fix(test): Use median of 100 trials to check solidity_abi gas costs

---

docker-compose.yml
server/args/src/declaration.rs
server/args/src/stack.rs
server/benches/perf/queue/tests.rs
server/src/dependency/heed.rs
server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs
server/src/dependency/shared.rs
server/src/lib.rs
server/src/main.rs
server/src/tests/integration.rs
server/src/tests/test_context.rs

Adds database parameters into the main `Config`.
- Add `Database` into `Config`
- Use the `Database` parameters in `create_db` functions
:green_circle: Fmt
:green_circle: Test
#45

feat(server-args): Add database configuration

---

Cargo.lock
api/src/methods/block_number.rs
api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
app/src/command.rs
app/src/query.rs
app/src/tests.rs
blockchain/Cargo.toml
blockchain/src/payload/in_memory.rs
blockchain/src/payload/mod.rs
blockchain/src/payload/read.rs
server/src/dependency/heed.rs
server/src/dependency/in_memory.rs
server/src/dependency/rocksdb.rs
storage/heed/src/payload.rs
storage/rocksdb/src/payload.rs

Adds a small in-memory cache for in-progress forkchoice update payloads (i.e. blocks). This cache allows the RPC to delay a bit for a block to finish building before returning a result from `engine_getPayload`, this preventing some unknown payload errors. The purpose of this change is to try to address the slowness of the faucet on Devnet.
- New synchronous (via `RwLock`) in-memory cache of in-progress blocks.
- RPC uses this cache to know when it should wait for a block to finish processing instead of returning an unknown payload error.
- Integration testing shows this change does have an improvement on deposit times
- This change will not necessarily stop all unknown payload errors. If the `engine_getPayload` call comes before the block even starts building (e.g. because the command …

Feat: keep track of in-progress payloads to avoid unknown payload errors

---

.github/workflows/deploy.yaml
docker-compose.yml

Adds cache configuration into `deploy` workflow.
In the best case it shaves off over an **hour and a quarter** as you can see in the difference between the two attempts of this workflow run https://github.com/UmiNetwork/op-move/actions/runs/15927637949.
- Add `cache_from` and `cache_to` imports and exports of cache layers
Using the CI

build(docker): Add cache configuration

---

server/args/src/declaration.rs

Fixes the genesis config being overwritten by the next config layer instead of merged.
- Merge genesis config layers instead of replacing it
Using docker

fix(server-args): Merge genesis config layers instead of replacing them

---

app/src/query.rs
server/src/lib.rs
server/src/mirror.rs
trie/src/constructor.rs
trie/src/lib.rs

Closes #203 
I audited all the `expect` calls in the code base. Most of them are about serialization (which should always succeed) or setting up genesis (which should cause panic if it fails). There were some that were part of unused code paths, so I simply deleted that unused code. In one case the `expect` could be replaced with `?`.
- Remove unused `FromOptRoot` trait
- Remove unused proxy to op-geth
- Replace expects with `?` in fee_history implementation

Fix(stability): Audit usage of `expect`

---

api/src/methods/get_block_by_hash.rs
api/src/methods/get_block_by_number.rs
api/src/methods/get_payload.rs
api/src/methods/mod.rs
api/src/methods/new_payload.rs
app/src/block_hash.rs
app/src/command.rs
app/src/tests.rs
blockchain/src/block/read.rs
blockchain/src/block/write.rs
server/benches/perf/queue/input.rs
server/src/lib.rs
server/src/tests/test_context.rs

With this we've cleaned up the suspicious field in/around API responses. Though size in bytes is definitely optional for block responses, geth at least does return it. Extra care was needed to be taken when calculating the byte size as the operation requires cloning and RLP encoding, so I tried to confine it to the write side of operations to allow it to be cheaply reconstructed on every block request.  
Closes #200.
- Changed the method name for block -> extended block conversion
- Extended the extended block repr to hold size as well
- Block size calculation at the block build stage

chore(api): return block size in RPC responses

---

.github/workflows/deploy.yaml

Deploy action in CI started failing after the most recent update to docker stack due to broken paths. That happened because the actual image used there was the one being pulled from the registry instead of the one built locally. This PR introduces a fix to that behavior and some rolling update tagging for peace of mind.
- Staged builds
- New `:previous` tag
Temporary added PR trigger to the action, will remove if successful.

fix(docker): build independent services first

---

Cargo.lock
api/Cargo.toml
api/src/jsonrpc.rs
api/src/methods/forkchoice_updated.rs
api/src/methods/get_payload.rs
api/src/methods/get_transaction_by_hash.rs
api/src/methods/get_transaction_receipt.rs
api/src/methods/new_payload.rs
api/src/request.rs
api/src/schema/engine.rs
app/src/command.rs
app/src/input.rs
app/src/mempool.rs
app/src/tests.rs
blockchain/src/transaction/write.rs
execution/src/tests/evm_native.rs
execution/src/transaction.rs
server/Cargo.toml
server/benches/perf/queue/input.rs
server/src/lib.rs
shared/src/primitives.rs

Make our engine API closer to the spec by running more validations. Some tests are still failing, and I'll probably write at least some new ones, but otherwise good to go.
Fixes #63.
- `forkchoiceUpdated` and `newPayload` with more thorough validation
- Some fresh fields from OP spec
- Changed the way mempool txs are treated. Instead of being drained unconditionally, they're only cleaned up at the end of block build now

refactor(api): make engine API closer to the spec

---

server/src/lib.rs

Closes #225 
Hooray for `alloy` having a one-liner for this!
- Compute genesis state root using L2 config.
- Checked against previously hard-coded state root.

Feat(genesis): Compute OP stack expected state root

---

execution/src/canonical.rs
execution/src/execute.rs
execution/src/simulate.rs

Closes #329 
- Refactor `execute_evm_contract` to take a struct instead of too many arguments.

Chore: Refactor execute_evm_contract to have fewer arguments

---

app/src/command.rs
app/src/query.rs
blockchain/src/block/gas.rs
blockchain/src/receipt/read.rs
blockchain/src/receipt/write.rs
blockchain/src/transaction/read.rs
blockchain/src/transaction/write.rs
execution/src/canonical.rs
execution/src/deposited.rs
execution/src/gas.rs
execution/src/session_id.rs
execution/src/simulate.rs
execution/src/tests/evm_native.rs
execution/src/tests/gas_cost.rs
execution/src/tests/transaction.rs
execution/src/tests/transfer.rs
execution/src/tests/utils.rs
execution/src/transaction.rs
server/src/lib.rs
shared/src/error.rs
storage/rocksdb/src/transaction.rs

Closes #227 
Closes #255 
This PR sets the gas price type based on alloy (u128 for general gas prices, u64 for base fee). Aptos only accepts u64 gas prices, so there is also a check at the start of executing canonical transaction that the gas price fits in a u64. It is an invalid transaction error if it does not fix because the priority fee is set as part of the transaction and the base fee is already a u64. Note this should never be a limitation in practice because a u64 variable can represent 18 ETH, and the smallest transaction costs 21k gas, which means if the gas price exceeds a u64 then even a basic transfer would cost millions of dollars; quite an unrealistic scenario.
- Represent general gas price as u128
- Represent base fee as u64.
- New `test_invalid_gas_price`

Chore: refactor gas price type as u128

---

api/src/methods/call.rs
server/src/tests/evm_contracts/account_storage.rs
server/src/tests/evm_contracts/block_env.rs
server/src/tests/test_context.rs

Change the `eth_call` response to hex string instead of byte array, since especially EVM SDKs expect this response.
- Encode `eth_call` response into hex string
Tested on a sample contract. Before the SDK would fail with:
```
TypeError: invalid BytesLike value (argument="value", value=[ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1 ], code=INVALID_ARGUMENT, version=6.14.4)
```
Now it parses the response correctly as a big number:
```
Count: 1n
```

Fix(API): Return hex string for byte arrays

---

api/Cargo.toml
api/src/json_utils.rs
api/src/method_name.rs
api/src/methods/get_payload.rs
api/src/methods/new_payload.rs
api/src/request.rs

First step toward OP bump support.
- Most changes to `newPayload` processing
- `getPayload` just falls back to V3 like `op-geth`
- feature gated one format check that interferes with old logic

feat(api): support engine API v4

---

api/src/methods/call.rs
api/src/methods/estimate_gas.rs
api/src/methods/forkchoice_updated.rs
api/src/methods/get_block_by_number.rs
api/src/methods/mod.rs
app/src/command.rs
app/src/tests.rs
blockchain/src/payload/read.rs

Some minute changes to the way payload attributes are handled around timestamps and in progress jobs.
Fixes #508.
- Ensure monotonic timestamp relative to parent
- Avoid sending block build commands for existing payloads
- Remove the respective payload from in progress map if the block build fails
When going through our main loop again, I noticed two very itchy issues that we never addressed, so I'll try to pick it up next:
* The actor is never automatically restarted on a failed built, but left hanging indefinitely, whereas we could have a supervisor of sorts to do just that
* There's no transactionality to the changes done during block build: e.g. if some DB access fails on receipt write, the Move/EVM changes would have already been committed and there's no rollback or anything, leaving …

fix(engine): harden payload handling

---

README.md
docker/Dockerfile.geth

Brings in this fix ethereum/go-ethereum#29955
Which is needed for proper restartability of the `geth` container.
- Upgrade `geth` version `1.14.5` => `1.14.6`
- Clone directly with a tag and minimal depth to decrease space usage of the `.git` directory
```
```

build(docker): Upgrade `geth` version `1.14.5` => `1.14.6`

---

.github/workflows/deploy.yaml
docker-compose.yml
docker/Dockerfile.op-move

The docker image toolchain and the workspace toolchain versions should match. If they won't then the workspace toolchain gets downloaded. It is then stored next to the image toolchain that won't get used at all.
- Start from the workspace rust toolchain for `op-move`
```
```

build(docker): Start from the workspace rust toolchain for `op-move`

---

docker/Dockerfile.geth
docker/Dockerfile.op-move
docker/geth-init.sh
docker/geth.sh

Runs the geth initialization during image build which includes:
* Initialize keystore for deterministic account addresses
* Prefund dev accounts
* Deploy Optimism factory deployer
It also brings:
* Graceful shutdown: When you stop the geth container, it actually propagates the SIGINT to the process and waits for it to properly finish.
* Restartability: Thanks to the graceful shutdown and #521 the container can be stopped and started again and will pickup exactly where it was stopped.
* Speed of docker operations: The geth container shutdown speed is now decreased from 10s to a couple of milliseconds. Mostly due to the fact that the interrupt signal reaches geth this time.
- Launch geth during image build and run initialization transactions
- Implement graceful shutdown for the geth …

build(docker): Initialize geth during image build

---

.github/workflows/deploy.yaml

Use [reproducible-containers/buildkit-cache-dance](https://github.com/reproducible-containers/buildkit-cache-dance) to restore cache mounts for caching Docker Rust builds.
- Add step that restores cached Docker mounts before running op-move image build
Using Github actions

ci: Cache Docker Rust mounts

---

docker/geth-init.sh
docker/op-node.sh

Moves the logic responsible for waiting for a finalized block with a positive timestamp from `op-node` container entrypoint to `geth` image build.
- Wait for finalized block with positive timestamp during `geth` image build
- Remove waiting for finalized block with positive timestamp from `op-node` entrypoint
```
docker stack deploy -c docker-compose.yml umi
```

build(docker): Wait for finalized block with positive timestamp during `geth` image build

---

server/src/lib.rs
server/src/main.rs

This goes along a similar vein as #512, but a cleaner solution of having dedicated runtimes for auth and http respectively.
- Serve futures are spawned separately on different RTs

refactor(server): have dedicated runtimes for auth and http routes

---

Cargo.lock
Cargo.toml
api/Cargo.toml
api/src/request.rs
app/Cargo.toml
app/src/command.rs
docker-compose.yml
server/Cargo.toml
server/src/main.rs

Exposes a scraping endpoint for metrics and instruments RPC request handling.
- Handler installation in main
- Metrics calls in API for RPC and in app for block build
Just `cargo check`. Will try to run it on a local stack later.
An alternative route was to make the endpoint available via warp, but this change was more minimal (as e.g. that would need different headers).
Besides the work here, I'll need to setup the so-called [Op Agent](https://cloud.google.com/monitoring/agent/ops-agent/prometheus) in GCP and restart the devnet, and hopefully we'll be able to see the new metrics in the [dashboard](https://console.cloud.google.com/monitoring/metrics-explorer;duration=P7D?hl=en&project=blockchain-451501) immediately after.

feat(server): expose prometheus endpoint

---

docker/op-proposer/entrypoint.sh
docker/shared/Dockerfile

Removes `jq` and uses grep + cut instead. Saves one dependency install during build and about 2 MB from the final image size.
- Remove `jq`
- Parse using grep + cut
```
```

build(docker): Remove dependency on `jq` from `op-proposer`
